In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Acris_Sales_Master_Export_Matched.csv')

/var/folders/x9/pvlqkpyj4qb8xt82bcch_6w00000gn/T/ipykernel_92649/3759680997.py:1: DtypeWarning: Columns (15,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Acris_Sales_Master_Export_Matched.csv')

In [4]:
df.describe()

,YEARBUILT,CONVERTED,SQFT,SALE_YEAR,SALE_MONTH,SALE_QUARTER,SALE_WEEK,LAST_90_DAYS,SALE_PRICE,PPSF,LISTED_PRICE,ZIP_CODE,BLOCK,LOT,HISTORY_ID,UNIT_ID
count,412812.000000,101557.000000,251457.000000,413981.000000,413981.000000,413981.000000,413981.000000,7327.000000,4.139810e+05,2.514570e+05,2.093100e+04,411824.000000,413981.000000,413981.000000,413981.000000,413981.000000
mean,1957.341453,1992.738472,1152.449107,2012.417949,6.531285,2.505132,26.700694,1.582503,1.319571e+06,1.158746e+03,1.259586e+06,10373.876272,1796.430285,3489.187586,257216.559400,133324.904174
std,57.723512,13.977193,2059.891222,6.738208,3.308658,1.076173,14.417217,0.493180,4.276110e+06,4.252897e+03,1.682562e+06,538.421094,1916.182803,3698.675831,159753.715174,88901.064027
min,0.000000,1900.000000,0.000000,1010.000000,1.000000,1.000000,1.000000,1.000000,5.000000e+04,0.000000e+00,1.850000e+03,0.000000,1.000000,1.000000,1.000000,1.000000
25%,1926.000000,1984.000000,700.000000,2007.000000,4.000000,2.000000,15.000000,1.000000,4.300000e+05,7.031400e+02,5.450000e+05,10017.000000,849.000000,25.000000,110874.000000,57264.000000
50%,1960.000000,1988.000000,950.000000,2012.000000,7.000000,3.000000,27.000000,2.000000,7.200000e+05,9.891600e+02,7.950000e+05,10025.000000,1241.000000,130.000000,262647.000000,121517.000000
75%,1998.000000,2006.000000,1350.000000,2017.000000,9.000000,3.000000,39.000000,2.000000,1.346126e+06,1.349430e+03,1.395000e+06,11201.000000,1756.000000,7501.000000,402687.000000,203358.000000
max,2029.000000,2025.000000,546410.000000,2023.000000,12.000000,4.000000,53.000000,2.000000,1.310000e+09,1.343284e+06,4.750000e+07,11355.000000,8824.000000,9034.000000,522603.000000,319710.000000

In [5]:
# make a copy of the dataframe
new_df = df.copy()

# make the column names lower case
new_df.columns = new_df.columns.str.lower()

# remove certains rows column flag Orange Flag, Yellow Flag, Red Flag, Inactive Flag and Oulier Flag
new_df = new_df[~new_df['flag'].isin(['Orange Flag', 'Yellow Flag', 'Red Flag', 'Inactive', 'Outlier'])]

len(new_df)

300345

In [1]:
metro = new_df[new_df['metro'].isin(['MAN', 'BK'])]
metro = metro[metro['sale_year'] > 2012]
# create a pivot table for average sale price each year by metro
yearly_avg_price = pd.pivot_table(metro, index=['metro', 'sale_year', "bldg_type"], values=['sale_price'], aggfunc='mean')
total_sales = pd.pivot_table(metro, index=['metro', 'sale_year', "bldg_type"], values=['sale_price'], aggfunc='count')
# remove year 2013 or less

print(yearly_avg_price)
print(total_sales)

NameError: name 'new_df' is not defined

In [31]:
# group by borough and sale price and by year and sum the sale price and yeaar <=2013 sort by year descending 
submarket = new_df.groupby(['submarket', 'sale_price', 'sale_year']).sum().sort_values(by=['sale_year'], ascending=False)

# create a pivot table with the index as submarket and the columns as sale year and the values as sale price

                                                                  buildingname
submarket                   sale_price sale_year
Yorkville                   32500000   2023                                  0  \
Riverside Dr./West End Ave. 1647000    2023                     The Chatsworth
Gramercy Park               930000     2023                        Park Towers
Riverside Dr./West End Ave. 1715000    2023                              Avery
Gramercy Park               935000     2023       Gramercy PlazaThe Penny Lane
                            937500     2023                    Gramercy Starck
Riverside Dr./West End Ave. 1710000    2023                                  0
Broadway Corridor           380000     2023                                  0
Gramercy Park               940000     2023                              Tempo
Riverside Dr./West End Ave. 1700000    2023                      The Clebourne

                                                   address
submarket                   sale_price sale_year
Yorkville                   32500000   2023            200  \
Riverside Dr./West End Ave. 1647000    2023            344
Gramercy Park               930000     2023            201
Riverside Dr./West End Ave. 1715000    2023            100
Gramercy Park               935000     2023       13039215
                            937500     2023            340
Riverside Dr./West End Ave. 1710000    2023            173
Broadway Corridor           380000     2023            230
Gramercy Park               940000     2023            300
Riverside Dr./West End Ave. 1700000    2023         230924

                                                                                             street
submarket                   sale_price sale_year
Yorkville                   32500000   2023                                        East 83rd Street  \
Riverside Dr./West End Ave. 1647000    2023                                        West 72nd Street
Gramercy Park               930000     2023                                        East 17th Street
Riverside Dr./West End Ave. 1715000    2023                                     Riverside Boulevard
Gramercy Park               935000     2023       East 18th StreetGramercy Park NorthEast 24th S...
                            937500     2023                                        East 23rd Street
Riverside Dr./West End Ave. 1710000    2023                                         Riverside Drive
Broadway Corridor           380000     2023                                         West End Avenue
Gramercy Park               940000     2023                                        East 23rd Street
Riverside Dr./West End Ave. 1700000    2023                          Riverside DriveWest End Avenue

                                                     bldg_type  yearbuilt
submarket                   sale_price sale_year
Yorkville                   32500000   2023              condo     2022.0  \
Riverside Dr./West End Ave. 1647000    2023               coop     1904.0
Gramercy Park               930000     2023               coop     1973.0
Riverside Dr./West End Ave. 1715000    2023              condo     2007.0
Gramercy Park               935000     2023       coopcoopcoop     5900.0
                            937500     2023              condo     2008.0
Riverside Dr./West End Ave. 1710000    2023               coop     1926.0
Broadway Corridor           380000     2023               coop     1927.0
Gramercy Park               940000     2023              condo     2009.0
Riverside Dr./West End Ave. 1700000    2023          condocoop     3844.0

                                                  converted      metro
submarket                   sale_price sale_year
Yorkville                   32500000   2023             0.0        MAN  \
Riverside Dr./West End Ave. 1647000    2023          2014.0        MAN
Gramercy Park               930000     2023          1983.0        MAN
Riverside Dr./West End Ave. 1715000    2023             0.0        MAN
Gramercy Park               935000     2023          1984.0  MANMANMAN
                            937500     2023             0.0        MAN
Riverside Dr./West End Ave. 1710000    2023          1968.0        MAN
Broadway Corridor           380000     2023             0.0        MAN
Gramercy Park               940000     2023             0.0        MAN
Riverside Dr./West End Ave. 1700000    2023          2005.0     MANMAN

                                                     market newdev     unit
submarket                   sale_price sale_year
Yorkville                   32500000   2023              ES      Y      PHC  \
Riverside Dr./West End Ave. 1647000    2023              WS      Y     1106
Gramercy Park               930000     2023             DWN      N      20A
Riverside Dr./West End Ave. 1715000    2023              WS      N      24A
Gramercy Park               935000     2023       DWNDWNDWN    NNN  4E9D115
                            937500     2023             DWN      N      11F
Riverside Dr./West End Ave. 1710000    2023              WS      N      11K
Broadway Corridor           380000     2023              WS      N       7B
Gramercy Park               940000     2023             DWN      N       4E
Riverside Dr./West End Ave. 1700000    2023            WSWS     NN    3A104

                                                  ... block   lot concierge
submarket                   sale_price sale_year  ...
Yorkville                   32500000   2023       ...  1528  7501         0  \
Riverside Dr./West End Ave. 1647000    2023       ...  1183    53         Y
Gramercy Park               930000     2023       ...   898     1         0
Riverside Dr./West End Ave. 1715000    2023       ...  1171  7505         Y
Gramercy Park               935000     2023       ...  2655    67         0
                            937500     2023       ...   928  7503         Y
Riverside Dr./West End Ave. 1710000    2023       ...  1250    67         0
Broadway Corridor           380000     2023       ...  1162     1         0
Gramercy Park               940000     2023       ...   928  7504         Y
Riverside Dr./West End Ave. 1700000    2023       ...  3130  7504         Y

                                                 ft_doorman pt_doorman
submarket                   sale_price sale_year
Yorkville                   32500000   2023               Y          0  \
Riverside Dr./West End Ave. 1647000    2023               Y          0
Gramercy Park               930000     2023               Y          0
Riverside Dr./West End Ave. 1715000    2023               Y          0
Gramercy Park               935000     2023             YYY          Y
                            937500     2023               Y          0
Riverside Dr./West End Ave. 1710000    2023               Y          0
Broadway Corridor           380000     2023               Y          0
Gramercy Park               940000     2023               Y          0
Riverside Dr./West End Ave. 1700000    2023              YY          0

                                                 attended_lobby
submarket                   sale_price sale_year
Yorkville                   32500000   2023                   Y  \
Riverside Dr./West End Ave. 1647000    2023                   Y
Gramercy Park               930000     2023                   0
Riverside Dr./West End Ave. 1715000    2023                   0
Gramercy Park               935000     2023                   0
                            937500     2023                   Y
Riverside Dr./West End Ave. 1710000    2023                   0
Broadway Corridor           380000     2023                   0
Gramercy Park               940000     2023                   Y
Riverside Dr./West End Ave. 1700000    2023                   Y

                                                                                                url
submarket                   sale_price sale_year
Yorkville                   32500000   2023       cityrealty.com/nyc/Yorkville/-200-east83rdstre...  \
Riverside Dr./West End Ave. 1647000    2023       cityrealty.com/nyc/RiversideDrWestEndAve/thech...
Gramercy Park               930000     2023       cityrealty.com/nyc/GramercyPark/parktowers-201...
Riverside Dr./West End Ave. 1715000    2023       cityrealty.com/nyc/RiversideDrWestEndAve/avery...
Gramercy Park               935000     2023       cityrealty.com/nyc/GramercyPark/gramercyplaza-...
                            937500     2023       cityrealty.com/nyc/GramercyPark/gramercystarck...
Riverside Dr./West End Ave. 1710000    2023       cityrealty.com/nyc/RiversideDrWestEndAve/-173-...
Broadway Corridor           380000     2023       cityrealty.com/nyc/BroadwayCorridor/-230-weste...
Gramercy Park               940000     2023       cityrealty.com/nyc/GramercyPark/tempo-300-east...
Riverside Dr./West End Ave. 1700000    2023       cityrealty.com/nyc/RiversideDrWestEndAve/-230-...

                                                                   date_recorded
submarket                   sale_price sale_year
Yorkville                   32500000   2023                           2023-09-19  \
Riverside Dr./West End Ave. 1647000    2023                           2023-09-07
Gramercy Park               930000     2023                           2023-01-24
Riverside Dr./West End Ave. 1715000    2023                           2023-07-01
Gramercy Park               935000     2023       2023-06-102023-07-212023-09-21
                            937500     2023                           2023-05-26
Riverside Dr./West End Ave. 1710000    2023                           2023-07-18
Broadway Corridor           380000     2023                           2023-03-15
Gramercy Park               940000     2023                           2023-07-11
Riverside Dr./West End Ave. 1700000    2023                 2023-06-252023-07-22

                                                  history_id  unit_id
submarket                   sale_price sale_year
Yorkville                   32500000   2023           520882   318790
Riverside Dr./West End Ave. 1647000    2023           520321   318443
Gramercy Park               930000     2023           508861   210166
Riverside Dr./West End Ave. 1715000    2023           516022    91927
Gramercy Park               935000     2023          1553895   480350
                            937500     2023           514504    60567
Riverside Dr./West End Ave. 1710000    2023           516708   316340
Broadway Corridor           380000     2023           511067   312807
Gramercy Park               940000     2023           516321   163263
Riverside Dr./West End Ave. 1700000    2023          1032690   342356

[10 rows x 44 columns]

In [27]:
%matplotlib inline

In [29]:
# plot the neighborhood and sale price by year
neigh.plot(kind='bar', figsize=(20,10))

KeyboardInterrupt: